### ISSUE TITLE
Image not found in README

### ISSUE THREAD

**Issue by maxwofford** [hackclub/banner#1]
![screenshot 2019-01-06 18 47 24](https://user-images.githubusercontent.com/5891442/50746367-8d74c800-11e3-11e9-8d83-1077d079ffaf.png)

I'm not sure what's supposed to show up in the README under the badge images, but it's not rendering correctly. The link is to https://camo.githubusercontent.com/3ed190243945c1180fcd4cb25a7d4c371e36f665/68747470733a2f2f6861636b636c75622e636f6d2f62616e6e6572, which is a 404

**Comment by lachlanjc** [comment]
This wasn't an image, just a syntax mistake
